name: CI/CD Pipeline

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
  workflow_dispatch: 

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend test
        working-directory: frontend
        run: npm test -- --run

  build:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest

      needs: test

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4


        - name: Login to dockerhub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build frontend  image
          run: |
            docker build -t $${{ secrets.DOCKERHUB_USERNAME }}/mern-docker-action-cicd-frontend:${IMAGE_TAG} ./frontend
        
        - name: Build backend image
          run: |
            docker build -t $${{ secrets.DOCKERHUB_USERNAME }}/mern-docker-action-cicd-backend:${IMAGE_TAG} ./backend

        - name: Push frontend image
          run: |
            docker push $${{ secrets.DOCKERHUB_USERNAME }}/mern-docker-action-cicd-frontend:${IMAGE_TAG}

        - name: Push frontend image
          run: |
            docker push $${{ secrets.DOCKERHUB_USERNAME }}/mern-docker-action-cicd-backend:${IMAGE_TAG}
        
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest@v4

    steps:
      - name: Deploy Application
        env: 
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          ssh \
            -o StrictHostKeyChecking=no \
            -i private_key \
            $EC2_USER@$EC2_HOST << EOF

              cd /home/ubuntu/mern-docker-cicd

              export IMAGE_TAG=${IMAGE_TAG}

              docker compose pull

              docker compuse up -d --remove-orphans --force-recreate

              docker image prune -f

            EOF

            rm -f private_key
          
